<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\DoTrack.Infrastructure\DoTrack.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\DoTrack.Migrations.Postgres\DoTrack.Migrations.Postgres.csproj" />
    <ProjectReference Include="..\..\src\DoTrack.Migrations.SqlServer\DoTrack.Migrations.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\DoTrack.Migrations.Sqlite\DoTrack.Migrations.Sqlite.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="Verify.XunitV3" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.MsSql" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
